<template>
  <div>
    <h3>本实例使用<a href="http://fontawesome.dashgame.com/">Font Awesome</a></h3>
    <p>通过cnpm i font-awesome -S安装</p>
    <p>目前还有一个问题，在打包之后，字体文件好像没有找到，所以导致图标显示不出来</p>
    <div class="icon-repository">
      <!--使用的时候注意版本，否则像下面这个无法显示-->
      <i class="fa fa-3x fa-glass"></i>
      <i class="fa fa-3x fa-music"></i>
      <i class="fa fa-3x fa-search"></i>
      <i class="fa fa-3x fa-envelope-o"></i>
      <i class="fa fa-3x fa-heart"></i>
      <i class="fa fa-3x fa-star"></i>
      <i class="fa fa-3x fa-star-o"></i>
      <i class="fa fa-3x fa-user"></i>
      <i class="fa fa-3x fa-film"></i>
      <i class="fa fa-3x fa-th-large"></i>
      <i class="fa fa-3x fa-th"></i>
      <i class="fa fa-3x fa-th-list"></i>
      <i class="fa fa-3x fa-check"></i>
      <i class="fa fa-3x fa-remove"></i>
      <i class="fa fa-3x fa-close"></i>
      <i class="fa fa-3x fa-times"></i>
      <i class="fa fa-3x fa-search-plus"></i>
      <i class="fa fa-3x fa-search-minus"></i>
      <i class="fa fa-3x fa-power-off"></i>
      <i class="fa fa-3x fa-signal"></i>
      <i class="fa fa-3x fa-gear"></i>
      <i class="fa fa-3x fa-cog"></i>
      <i class="fa fa-3x fa-trash-o"></i>
      <i class="fa fa-3x fa-home"></i>
      <i class="fa fa-3x fa-file-o"></i>
      <i class="fa fa-3x fa-clock-o"></i>
      <i class="fa fa-3x fa-road"></i>
      <i class="fa fa-3x fa-download"></i>
      <i class="fa fa-3x fa-arrow-circle-o-down"></i>
      <i class="fa fa-3x fa-arrow-circle-o-up"></i>
      <i class="fa fa-3x fa-inbox"></i>
      <i class="fa fa-3x fa-play-circle-o"></i>
      <i class="fa fa-3x fa-rotate-right"></i>
      <i class="fa fa-3x fa-repeat"></i>
      <i class="fa fa-3x fa-refresh"></i>
      <i class="fa fa-3x fa-list-alt"></i>
      <i class="fa fa-3x fa-lock"></i>
      <i class="fa fa-3x fa-flag"></i>
      <i class="fa fa-3x fa-headphones"></i>
      <i class="fa fa-3x fa-volume-off"></i>
      <i class="fa fa-3x fa-volume-down"></i>
      <i class="fa fa-3x fa-volume-up"></i>
      <i class="fa fa-3x fa-qrcode"></i>
      <i class="fa fa-3x fa-barcode"></i>
      <i class="fa fa-3x fa-tag"></i>
      <i class="fa fa-3x fa-tags"></i>
      <i class="fa fa-3x fa-book"></i>
      <i class="fa fa-3x fa-bookmark"></i>
      <i class="fa fa-3x fa-print"></i>
      <i class="fa fa-3x fa-camera"></i>
      <i class="fa fa-3x fa-font"></i>
      <i class="fa fa-3x fa-bold"></i>
      <i class="fa fa-3x fa-italic"></i>
      <i class="fa fa-3x fa-text-height"></i>
      <i class="fa fa-3x fa-text-width"></i>
      <i class="fa fa-3x fa-align-left"></i>
      <i class="fa fa-3x fa-align-center"></i>
      <i class="fa fa-3x fa-align-right"></i>
      <i class="fa fa-3x fa-align-justify"></i>
      <i class="fa fa-3x fa-list"></i>
      <i class="fa fa-3x fa-dedent"></i>
      <i class="fa fa-3x fa-outdent"></i>
      <i class="fa fa-3x fa-indent"></i>
      <i class="fa fa-3x fa-video-camera"></i>
      <i class="fa fa-3x fa-photo"></i>
      <i class="fa fa-3x fa-image"></i>
      <i class="fa fa-3x fa-picture-o"></i>
      <i class="fa fa-3x fa-pencil"></i>
      <i class="fa fa-3x fa-map-marker"></i>
      <i class="fa fa-3x fa-adjust"></i>
      <i class="fa fa-3x fa-tint"></i>
      <i class="fa fa-3x fa-edit"></i>
      <i class="fa fa-3x fa-pencil-square-o"></i>
      <i class="fa fa-3x fa-share-square-o"></i>
      <i class="fa fa-3x fa-check-square-o"></i>
      <i class="fa fa-3x fa-arrows"></i>
      <i class="fa fa-3x fa-step-backward"></i>
      <i class="fa fa-3x fa-fast-backward"></i>
      <i class="fa fa-3x fa-backward"></i>
      <i class="fa fa-3x fa-play"></i>
      <i class="fa fa-3x fa-pause"></i>
      <i class="fa fa-3x fa-stop"></i>
      <i class="fa fa-3x fa-forward"></i>
      <i class="fa fa-3x fa-fast-forward"></i>
      <i class="fa fa-3x fa-step-forward"></i>
      <i class="fa fa-3x fa-eject"></i>
      <i class="fa fa-3x fa-chevron-left"></i>
      <i class="fa fa-3x fa-chevron-right"></i>
      <i class="fa fa-3x fa-plus-circle"></i>
      <i class="fa fa-3x fa-minus-circle"></i>
      <i class="fa fa-3x fa-times-circle"></i>
      <i class="fa fa-3x fa-check-circle"></i>
      <i class="fa fa-3x fa-question-circle"></i>
      <i class="fa fa-3x fa-info-circle"></i>
      <i class="fa fa-3x fa-crosshairs"></i>
      <i class="fa fa-3x fa-times-circle-o"></i>
      <i class="fa fa-3x fa-check-circle-o"></i>
      <i class="fa fa-3x fa-ban"></i>
      <i class="fa fa-3x fa-arrow-left"></i>
      <i class="fa fa-3x fa-arrow-right"></i>
      <i class="fa fa-3x fa-arrow-up"></i>
      <i class="fa fa-3x fa-arrow-down"></i>
      <i class="fa fa-3x fa-mail-forward"></i>
      <i class="fa fa-3x fa-share"></i>
      <i class="fa fa-3x fa-expand"></i>
      <i class="fa fa-3x fa-compress"></i>
      <i class="fa fa-3x fa-plus"></i>
      <i class="fa fa-3x fa-minus"></i>
      <i class="fa fa-3x fa-asterisk"></i>
      <i class="fa fa-3x fa-exclamation-circle"></i>
      <i class="fa fa-3x fa-gift"></i>
      <i class="fa fa-3x fa-leaf"></i>
      <i class="fa fa-3x fa-fire"></i>
      <i class="fa fa-3x fa-eye"></i>
      <i class="fa fa-3x fa-eye-slash"></i>
      <i class="fa fa-3x fa-warning"></i>
      <i class="fa fa-3x fa-exclamation-triangle"></i>
      <i class="fa fa-3x fa-plane"></i>
      <i class="fa fa-3x fa-calendar"></i>
      <i class="fa fa-3x fa-random"></i>
      <i class="fa fa-3x fa-comment"></i>
      <i class="fa fa-3x fa-magnet"></i>
      <i class="fa fa-3x fa-chevron-up"></i>
      <i class="fa fa-3x fa-chevron-down"></i>
      <i class="fa fa-3x fa-retweet"></i>
      <i class="fa fa-3x fa-shopping-cart"></i>
      <i class="fa fa-3x fa-folder"></i>
      <i class="fa fa-3x fa-folder-open"></i>
      <i class="fa fa-3x fa-arrows-v"></i>
      <i class="fa fa-3x fa-arrows-h"></i>
      <i class="fa fa-3x fa-bar-chart-o"></i>
      <i class="fa fa-3x fa-bar-chart"></i>
      <i class="fa fa-3x fa-twitter-square"></i>
      <i class="fa fa-3x fa-facebook-square"></i>
      <i class="fa fa-3x fa-camera-retro"></i>
      <i class="fa fa-3x fa-key"></i>
      <i class="fa fa-3x fa-gears"></i>
      <i class="fa fa-3x fa-cogs"></i>
      <i class="fa fa-3x fa-comments"></i>
      <i class="fa fa-3x fa-thumbs-o-up"></i>
      <i class="fa fa-3x fa-thumbs-o-down"></i>
      <i class="fa fa-3x fa-star-half"></i>
      <i class="fa fa-3x fa-heart-o"></i>
      <i class="fa fa-3x fa-sign-out"></i>
      <i class="fa fa-3x fa-linkedin-square"></i>
      <i class="fa fa-3x fa-thumb-tack"></i>
      <i class="fa fa-3x fa-external-link"></i>
      <i class="fa fa-3x fa-sign-in"></i>
      <i class="fa fa-3x fa-trophy"></i>
      <i class="fa fa-3x fa-github-square"></i>
      <i class="fa fa-3x fa-upload"></i>
      <i class="fa fa-3x fa-lemon-o"></i>
      <i class="fa fa-3x fa-phone"></i>
      <i class="fa fa-3x fa-square-o"></i>
      <i class="fa fa-3x fa-bookmark-o"></i>
      <i class="fa fa-3x fa-phone-square"></i>
      <i class="fa fa-3x fa-twitter"></i>
      <i class="fa fa-3x fa-facebook-f"></i>
      <i class="fa fa-3x fa-facebook"></i>
      <i class="fa fa-3x fa-github"></i>
      <i class="fa fa-3x fa-unlock"></i>
      <i class="fa fa-3x fa-credit-card"></i>
      <i class="fa fa-3x fa-feed"></i>
      <i class="fa fa-3x fa-rss"></i>
      <i class="fa fa-3x fa-hdd-o"></i>
      <i class="fa fa-3x fa-bullhorn"></i>
      <i class="fa fa-3x fa-bell"></i>
      <i class="fa fa-3x fa-certificate"></i>
      <i class="fa fa-3x fa-hand-o-right"></i>
      <i class="fa fa-3x fa-hand-o-left"></i>
      <i class="fa fa-3x fa-hand-o-up"></i>
      <i class="fa fa-3x fa-hand-o-down"></i>
      <i class="fa fa-3x fa-arrow-circle-left"></i>
      <i class="fa fa-3x fa-arrow-circle-right"></i>
      <i class="fa fa-3x fa-arrow-circle-up"></i>
      <i class="fa fa-3x fa-arrow-circle-down"></i>
      <i class="fa fa-3x fa-globe"></i>
      <i class="fa fa-3x fa-wrench"></i>
      <i class="fa fa-3x fa-tasks"></i>
      <i class="fa fa-3x fa-filter"></i>
      <i class="fa fa-3x fa-briefcase"></i>
      <i class="fa fa-3x fa-arrows-alt"></i>
      <i class="fa fa-3x fa-group"></i>
      <i class="fa fa-3x fa-users"></i>
      <i class="fa fa-3x fa-chain"></i>
      <i class="fa fa-3x fa-link"></i>
      <i class="fa fa-3x fa-cloud"></i>
      <i class="fa fa-3x fa-flask"></i>
      <i class="fa fa-3x fa-cut"></i>
      <i class="fa fa-3x fa-scissors"></i>
      <i class="fa fa-3x fa-copy"></i>
      <i class="fa fa-3x fa-files-o"></i>
      <i class="fa fa-3x fa-paperclip"></i>
      <i class="fa fa-3x fa-save"></i>
      <i class="fa fa-3x fa-floppy-o"></i>
      <i class="fa fa-3x fa-square"></i>
      <i class="fa fa-3x fa-navicon"></i>
      <i class="fa fa-3x fa-reorder"></i>
      <i class="fa fa-3x fa-bars"></i>
      <i class="fa fa-3x fa-list-ul"></i>
      <i class="fa fa-3x fa-list-ol"></i>
      <i class="fa fa-3x fa-strikethrough"></i>
      <i class="fa fa-3x fa-underline"></i>
      <i class="fa fa-3x fa-table"></i>
      <i class="fa fa-3x fa-magic"></i>
      <i class="fa fa-3x fa-truck"></i>
      <i class="fa fa-3x fa-pinterest"></i>
      <i class="fa fa-3x fa-pinterest-square"></i>
      <i class="fa fa-3x fa-google-plus-square"></i>
      <i class="fa fa-3x fa-google-plus"></i>
      <i class="fa fa-3x fa-money"></i>
      <i class="fa fa-3x fa-caret-down"></i>
      <i class="fa fa-3x fa-caret-up"></i>
      <i class="fa fa-3x fa-caret-left"></i>
      <i class="fa fa-3x fa-caret-right"></i>
      <i class="fa fa-3x fa-columns"></i>
      <i class="fa fa-3x fa-unsorted"></i>
      <i class="fa fa-3x fa-sort"></i>
      <i class="fa fa-3x fa-sort-down"></i>
      <i class="fa fa-3x fa-sort-desc"></i>
      <i class="fa fa-3x fa-sort-up"></i>
      <i class="fa fa-3x fa-sort-asc"></i>
      <i class="fa fa-3x fa-envelope"></i>
      <i class="fa fa-3x fa-linkedin"></i>
      <i class="fa fa-3x fa-rotate-left"></i>
      <i class="fa fa-3x fa-undo"></i>
      <i class="fa fa-3x fa-legal"></i>
      <i class="fa fa-3x fa-gavel"></i>
      <i class="fa fa-3x fa-dashboard"></i>
      <i class="fa fa-3x fa-tachometer"></i>
      <i class="fa fa-3x fa-comment-o"></i>
      <i class="fa fa-3x fa-comments-o"></i>
      <i class="fa fa-3x fa-flash"></i>
      <i class="fa fa-3x fa-bolt"></i>
      <i class="fa fa-3x fa-sitemap"></i>
      <i class="fa fa-3x fa-umbrella"></i>
      <i class="fa fa-3x fa-paste"></i>
      <i class="fa fa-3x fa-clipboard"></i>
      <i class="fa fa-3x fa-lightbulb-o"></i>
      <i class="fa fa-3x fa-exchange"></i>
      <i class="fa fa-3x fa-cloud-download"></i>
      <i class="fa fa-3x fa-cloud-upload"></i>
      <i class="fa fa-3x fa-user-md"></i>
      <i class="fa fa-3x fa-stethoscope"></i>
      <i class="fa fa-3x fa-suitcase"></i>
      <i class="fa fa-3x fa-bell-o"></i>
      <i class="fa fa-3x fa-coffee"></i>
      <i class="fa fa-3x fa-cutlery"></i>
      <i class="fa fa-3x fa-file-text-o"></i>
      <i class="fa fa-3x fa-building-o"></i>
      <i class="fa fa-3x fa-hospital-o"></i>
      <i class="fa fa-3x fa-ambulance"></i>
      <i class="fa fa-3x fa-medkit"></i>
      <i class="fa fa-3x fa-fighter-jet"></i>
      <i class="fa fa-3x fa-beer"></i>
      <i class="fa fa-3x fa-h-square"></i>
      <i class="fa fa-3x fa-plus-square"></i>
      <i class="fa fa-3x fa-angle-double-left"></i>
      <i class="fa fa-3x fa-angle-double-right"></i>
      <i class="fa fa-3x fa-angle-double-up"></i>
      <i class="fa fa-3x fa-angle-double-down"></i>
      <i class="fa fa-3x fa-angle-left"></i>
      <i class="fa fa-3x fa-angle-right"></i>
      <i class="fa fa-3x fa-angle-up"></i>
      <i class="fa fa-3x fa-angle-down"></i>
      <i class="fa fa-3x fa-desktop"></i>
      <i class="fa fa-3x fa-laptop"></i>
      <i class="fa fa-3x fa-tablet"></i>
      <i class="fa fa-3x fa-mobile-phone"></i>
      <i class="fa fa-3x fa-mobile"></i>
      <i class="fa fa-3x fa-circle-o"></i>
      <i class="fa fa-3x fa-quote-left"></i>
      <i class="fa fa-3x fa-quote-right"></i>
      <i class="fa fa-3x fa-spinner"></i>
      <i class="fa fa-3x fa-circle"></i>
      <i class="fa fa-3x fa-mail-reply"></i>
      <i class="fa fa-3x fa-reply"></i>
      <i class="fa fa-3x fa-github-alt"></i>
      <i class="fa fa-3x fa-folder-o"></i>
      <i class="fa fa-3x fa-folder-open-o"></i>
      <i class="fa fa-3x fa-smile-o"></i>
      <i class="fa fa-3x fa-frown-o"></i>
      <i class="fa fa-3x fa-meh-o"></i>
      <i class="fa fa-3x fa-gamepad"></i>
      <i class="fa fa-3x fa-keyboard-o"></i>
      <i class="fa fa-3x fa-flag-o"></i>
      <i class="fa fa-3x fa-flag-checkered"></i>
      <i class="fa fa-3x fa-terminal"></i>
      <i class="fa fa-3x fa-code"></i>
      <i class="fa fa-3x fa-mail-reply-all"></i>
      <i class="fa fa-3x fa-reply-all"></i>
      <i class="fa fa-3x fa-star-half-empty"></i>
      <i class="fa fa-3x fa-star-half-full"></i>
      <i class="fa fa-3x fa-star-half-o"></i>
      <i class="fa fa-3x fa-location-arrow"></i>
      <i class="fa fa-3x fa-crop"></i>
      <i class="fa fa-3x fa-code-fork"></i>
      <i class="fa fa-3x fa-unlink"></i>
      <i class="fa fa-3x fa-chain-broken"></i>
      <i class="fa fa-3x fa-question"></i>
      <i class="fa fa-3x fa-info"></i>
      <i class="fa fa-3x fa-exclamation"></i>
      <i class="fa fa-3x fa-superscript"></i>
      <i class="fa fa-3x fa-subscript"></i>
      <i class="fa fa-3x fa-eraser"></i>
      <i class="fa fa-3x fa-puzzle-piece"></i>
      <i class="fa fa-3x fa-microphone"></i>
      <i class="fa fa-3x fa-microphone-slash"></i>
      <i class="fa fa-3x fa-shield"></i>
      <i class="fa fa-3x fa-calendar-o"></i>
      <i class="fa fa-3x fa-fire-extinguisher"></i>
      <i class="fa fa-3x fa-rocket"></i>
      <i class="fa fa-3x fa-maxcdn"></i>
      <i class="fa fa-3x fa-chevron-circle-left"></i>
      <i class="fa fa-3x fa-chevron-circle-right"></i>
      <i class="fa fa-3x fa-chevron-circle-up"></i>
      <i class="fa fa-3x fa-chevron-circle-down"></i>
      <i class="fa fa-3x fa-html5"></i>
      <i class="fa fa-3x fa-css3"></i>
      <i class="fa fa-3x fa-anchor"></i>
      <i class="fa fa-3x fa-unlock-alt"></i>
      <i class="fa fa-3x fa-bullseye"></i>
      <i class="fa fa-3x fa-ellipsis-h"></i>
      <i class="fa fa-3x fa-ellipsis-v"></i>
      <i class="fa fa-3x fa-rss-square"></i>
      <i class="fa fa-3x fa-play-circle"></i>
      <i class="fa fa-3x fa-ticket"></i>
      <i class="fa fa-3x fa-minus-square"></i>
      <i class="fa fa-3x fa-minus-square-o"></i>
      <i class="fa fa-3x fa-level-up"></i>
      <i class="fa fa-3x fa-level-down"></i>
      <i class="fa fa-3x fa-check-square"></i>
      <i class="fa fa-3x fa-pencil-square"></i>
      <i class="fa fa-3x fa-external-link-square"></i>
      <i class="fa fa-3x fa-share-square"></i>
      <i class="fa fa-3x fa-compass"></i>
      <i class="fa fa-3x fa-toggle-down"></i>
      <i class="fa fa-3x fa-caret-square-o-down"></i>
      <i class="fa fa-3x fa-toggle-up"></i>
      <i class="fa fa-3x fa-caret-square-o-up"></i>
      <i class="fa fa-3x fa-toggle-right"></i>
      <i class="fa fa-3x fa-caret-square-o-right"></i>
      <i class="fa fa-3x fa-euro"></i>
      <i class="fa fa-3x fa-eur"></i>
      <i class="fa fa-3x fa-gbp"></i>
      <i class="fa fa-3x fa-dollar"></i>
      <i class="fa fa-3x fa-usd"></i>
      <i class="fa fa-3x fa-rupee"></i>
      <i class="fa fa-3x fa-inr"></i>
      <i class="fa fa-3x fa-cny"></i>
      <i class="fa fa-3x fa-rmb"></i>
      <i class="fa fa-3x fa-yen"></i>
      <i class="fa fa-3x fa-jpy"></i>
      <i class="fa fa-3x fa-ruble"></i>
      <i class="fa fa-3x fa-rouble"></i>
      <i class="fa fa-3x fa-rub"></i>
      <i class="fa fa-3x fa-won"></i>
      <i class="fa fa-3x fa-krw"></i>
      <i class="fa fa-3x fa-bitcoin"></i>
      <i class="fa fa-3x fa-btc"></i>
      <i class="fa fa-3x fa-file"></i>
      <i class="fa fa-3x fa-file-text"></i>
      <i class="fa fa-3x fa-sort-alpha-asc"></i>
      <i class="fa fa-3x fa-sort-alpha-desc"></i>
      <i class="fa fa-3x fa-sort-amount-asc"></i>
      <i class="fa fa-3x fa-sort-amount-desc"></i>
      <i class="fa fa-3x fa-sort-numeric-asc"></i>
      <i class="fa fa-3x fa-sort-numeric-desc"></i>
      <i class="fa fa-3x fa-thumbs-up"></i>
      <i class="fa fa-3x fa-thumbs-down"></i>
      <i class="fa fa-3x fa-youtube-square"></i>
      <i class="fa fa-3x fa-youtube"></i>
      <i class="fa fa-3x fa-xing"></i>
      <i class="fa fa-3x fa-xing-square"></i>
      <i class="fa fa-3x fa-youtube-play"></i>
      <i class="fa fa-3x fa-dropbox"></i>
      <i class="fa fa-3x fa-stack-overflow"></i>
      <i class="fa fa-3x fa-instagram"></i>
      <i class="fa fa-3x fa-flickr"></i>
      <i class="fa fa-3x fa-adn"></i>
      <i class="fa fa-3x fa-bitbucket"></i>
      <i class="fa fa-3x fa-bitbucket-square"></i>
      <i class="fa fa-3x fa-tumblr"></i>
      <i class="fa fa-3x fa-tumblr-square"></i>
      <i class="fa fa-3x fa-long-arrow-down"></i>
      <i class="fa fa-3x fa-long-arrow-up"></i>
      <i class="fa fa-3x fa-long-arrow-left"></i>
      <i class="fa fa-3x fa-long-arrow-right"></i>
      <i class="fa fa-3x fa-apple"></i>
      <i class="fa fa-3x fa-windows"></i>
      <i class="fa fa-3x fa-android"></i>
      <i class="fa fa-3x fa-linux"></i>
      <i class="fa fa-3x fa-dribbble"></i>
      <i class="fa fa-3x fa-skype"></i>
      <i class="fa fa-3x fa-foursquare"></i>
      <i class="fa fa-3x fa-trello"></i>
      <i class="fa fa-3x fa-female"></i>
      <i class="fa fa-3x fa-male"></i>
      <i class="fa fa-3x fa-gittip"></i>
      <i class="fa fa-3x fa-gratipay"></i>
      <i class="fa fa-3x fa-sun-o"></i>
      <i class="fa fa-3x fa-moon-o"></i>
      <i class="fa fa-3x fa-archive"></i>
      <i class="fa fa-3x fa-bug"></i>
      <i class="fa fa-3x fa-vk"></i>
      <i class="fa fa-3x fa-weibo"></i>
      <i class="fa fa-3x fa-renren"></i>
      <i class="fa fa-3x fa-pagelines"></i>
      <i class="fa fa-3x fa-stack-exchange"></i>
      <i class="fa fa-3x fa-arrow-circle-o-right"></i>
      <i class="fa fa-3x fa-arrow-circle-o-left"></i>
      <i class="fa fa-3x fa-toggle-left"></i>
      <i class="fa fa-3x fa-caret-square-o-left"></i>
      <i class="fa fa-3x fa-dot-circle-o"></i>
      <i class="fa fa-3x fa-wheelchair"></i>
      <i class="fa fa-3x fa-vimeo-square"></i>
      <i class="fa fa-3x fa-turkish-lira"></i>
      <i class="fa fa-3x fa-try"></i>
      <i class="fa fa-3x fa-plus-square-o"></i>
      <i class="fa fa-3x fa-space-shuttle"></i>
      <i class="fa fa-3x fa-slack"></i>
      <i class="fa fa-3x fa-envelope-square"></i>
      <i class="fa fa-3x fa-wordpress"></i>
      <i class="fa fa-3x fa-openid"></i>
      <i class="fa fa-3x fa-institution"></i>
      <i class="fa fa-3x fa-bank"></i>
      <i class="fa fa-3x fa-university"></i>
      <i class="fa fa-3x fa-mortar-board"></i>
      <i class="fa fa-3x fa-graduation-cap"></i>
      <i class="fa fa-3x fa-yahoo"></i>
      <i class="fa fa-3x fa-google"></i>
      <i class="fa fa-3x fa-reddit"></i>
      <i class="fa fa-3x fa-reddit-square"></i>
      <i class="fa fa-3x fa-stumbleupon-circle"></i>
      <i class="fa fa-3x fa-stumbleupon"></i>
      <i class="fa fa-3x fa-delicious"></i>
      <i class="fa fa-3x fa-digg"></i>
      <i class="fa fa-3x fa-pied-piper-pp"></i>
      <i class="fa fa-3x fa-pied-piper-alt"></i>
      <i class="fa fa-3x fa-drupal"></i>
      <i class="fa fa-3x fa-joomla"></i>
      <i class="fa fa-3x fa-language"></i>
      <i class="fa fa-3x fa-fax"></i>
      <i class="fa fa-3x fa-building"></i>
      <i class="fa fa-3x fa-child"></i>
      <i class="fa fa-3x fa-paw"></i>
      <i class="fa fa-3x fa-spoon"></i>
      <i class="fa fa-3x fa-cube"></i>
      <i class="fa fa-3x fa-cubes"></i>
      <i class="fa fa-3x fa-behance"></i>
      <i class="fa fa-3x fa-behance-square"></i>
      <i class="fa fa-3x fa-steam"></i>
      <i class="fa fa-3x fa-steam-square"></i>
      <i class="fa fa-3x fa-recycle"></i>
      <i class="fa fa-3x fa-automobile"></i>
      <i class="fa fa-3x fa-car"></i>
      <i class="fa fa-3x fa-cab"></i>
      <i class="fa fa-3x fa-taxi"></i>
      <i class="fa fa-3x fa-tree"></i>
      <i class="fa fa-3x fa-spotify"></i>
      <i class="fa fa-3x fa-deviantart"></i>
      <i class="fa fa-3x fa-soundcloud"></i>
      <i class="fa fa-3x fa-database"></i>
      <i class="fa fa-3x fa-file-pdf-o"></i>
      <i class="fa fa-3x fa-file-word-o"></i>
      <i class="fa fa-3x fa-file-excel-o"></i>
      <i class="fa fa-3x fa-file-powerpoint-o"></i>
      <i class="fa fa-3x fa-file-photo-o"></i>
      <i class="fa fa-3x fa-file-picture-o"></i>
      <i class="fa fa-3x fa-file-image-o"></i>
      <i class="fa fa-3x fa-file-zip-o"></i>
      <i class="fa fa-3x fa-file-archive-o"></i>
      <i class="fa fa-3x fa-file-sound-o"></i>
      <i class="fa fa-3x fa-file-audio-o"></i>
      <i class="fa fa-3x fa-file-movie-o"></i>
      <i class="fa fa-3x fa-file-video-o"></i>
      <i class="fa fa-3x fa-file-code-o"></i>
      <i class="fa fa-3x fa-vine"></i>
      <i class="fa fa-3x fa-codepen"></i>
      <i class="fa fa-3x fa-jsfiddle"></i>
      <i class="fa fa-3x fa-life-bouy"></i>
      <i class="fa fa-3x fa-life-buoy"></i>
      <i class="fa fa-3x fa-life-saver"></i>
      <i class="fa fa-3x fa-support"></i>
      <i class="fa fa-3x fa-life-ring"></i>
      <i class="fa fa-3x fa-circle-o-notch"></i>
      <i class="fa fa-3x fa-ra"></i>
      <i class="fa fa-3x fa-resistance"></i>
      <i class="fa fa-3x fa-rebel"></i>
      <i class="fa fa-3x fa-ge"></i>
      <i class="fa fa-3x fa-empire"></i>
      <i class="fa fa-3x fa-git-square"></i>
      <i class="fa fa-3x fa-git"></i>
      <i class="fa fa-3x fa-y-combinator-square"></i>
      <i class="fa fa-3x fa-yc-square"></i>
      <i class="fa fa-3x fa-hacker-news"></i>
      <i class="fa fa-3x fa-tencent-weibo"></i>
      <i class="fa fa-3x fa-qq"></i>
      <i class="fa fa-3x fa-wechat"></i>
      <i class="fa fa-3x fa-weixin"></i>
      <i class="fa fa-3x fa-send"></i>
      <i class="fa fa-3x fa-paper-plane"></i>
      <i class="fa fa-3x fa-send-o"></i>
      <i class="fa fa-3x fa-paper-plane-o"></i>
      <i class="fa fa-3x fa-history"></i>
      <i class="fa fa-3x fa-circle-thin"></i>
      <i class="fa fa-3x fa-header"></i>
      <i class="fa fa-3x fa-paragraph"></i>
      <i class="fa fa-3x fa-sliders"></i>
      <i class="fa fa-3x fa-share-alt"></i>
      <i class="fa fa-3x fa-share-alt-square"></i>
      <i class="fa fa-3x fa-bomb"></i>
      <i class="fa fa-3x fa-soccer-ball-o"></i>
      <i class="fa fa-3x fa-futbol-o"></i>
      <i class="fa fa-3x fa-tty"></i>
      <i class="fa fa-3x fa-binoculars"></i>
      <i class="fa fa-3x fa-plug"></i>
      <i class="fa fa-3x fa-slideshare"></i>
      <i class="fa fa-3x fa-twitch"></i>
      <i class="fa fa-3x fa-yelp"></i>
      <i class="fa fa-3x fa-newspaper-o"></i>
      <i class="fa fa-3x fa-wifi"></i>
      <i class="fa fa-3x fa-calculator"></i>
      <i class="fa fa-3x fa-paypal"></i>
      <i class="fa fa-3x fa-google-wallet"></i>
      <i class="fa fa-3x fa-cc-visa"></i>
      <i class="fa fa-3x fa-cc-mastercard"></i>
      <i class="fa fa-3x fa-cc-discover"></i>
      <i class="fa fa-3x fa-cc-amex"></i>
      <i class="fa fa-3x fa-cc-paypal"></i>
      <i class="fa fa-3x fa-cc-stripe"></i>
      <i class="fa fa-3x fa-bell-slash"></i>
      <i class="fa fa-3x fa-bell-slash-o"></i>
      <i class="fa fa-3x fa-trash"></i>
      <i class="fa fa-3x fa-copyright"></i>
      <i class="fa fa-3x fa-at"></i>
      <i class="fa fa-3x fa-eyedropper"></i>
      <i class="fa fa-3x fa-paint-brush"></i>
      <i class="fa fa-3x fa-birthday-cake"></i>
      <i class="fa fa-3x fa-area-chart"></i>
      <i class="fa fa-3x fa-pie-chart"></i>
      <i class="fa fa-3x fa-line-chart"></i>
      <i class="fa fa-3x fa-lastfm"></i>
      <i class="fa fa-3x fa-lastfm-square"></i>
      <i class="fa fa-3x fa-toggle-off"></i>
      <i class="fa fa-3x fa-toggle-on"></i>
      <i class="fa fa-3x fa-bicycle"></i>
      <i class="fa fa-3x fa-bus"></i>
      <i class="fa fa-3x fa-ioxhost"></i>
      <i class="fa fa-3x fa-angellist"></i>
      <i class="fa fa-3x fa-cc"></i>
      <i class="fa fa-3x fa-shekel"></i>
      <i class="fa fa-3x fa-sheqel"></i>
      <i class="fa fa-3x fa-ils"></i>
      <i class="fa fa-3x fa-meanpath"></i>
      <i class="fa fa-3x fa-buysellads"></i>
      <i class="fa fa-3x fa-connectdevelop"></i>
      <i class="fa fa-3x fa-dashcube"></i>
      <i class="fa fa-3x fa-forumbee"></i>
      <i class="fa fa-3x fa-leanpub"></i>
      <i class="fa fa-3x fa-sellsy"></i>
      <i class="fa fa-3x fa-shirtsinbulk"></i>
      <i class="fa fa-3x fa-simplybuilt"></i>
      <i class="fa fa-3x fa-skyatlas"></i>
      <i class="fa fa-3x fa-cart-plus"></i>
      <i class="fa fa-3x fa-cart-arrow-down"></i>
      <i class="fa fa-3x fa-diamond"></i>
      <i class="fa fa-3x fa-ship"></i>
      <i class="fa fa-3x fa-user-secret"></i>
      <i class="fa fa-3x fa-motorcycle"></i>
      <i class="fa fa-3x fa-street-view"></i>
      <i class="fa fa-3x fa-heartbeat"></i>
      <i class="fa fa-3x fa-venus"></i>
      <i class="fa fa-3x fa-mars"></i>
      <i class="fa fa-3x fa-mercury"></i>
      <i class="fa fa-3x fa-intersex"></i>
      <i class="fa fa-3x fa-transgender"></i>
      <i class="fa fa-3x fa-transgender-alt"></i>
      <i class="fa fa-3x fa-venus-double"></i>
      <i class="fa fa-3x fa-mars-double"></i>
      <i class="fa fa-3x fa-venus-mars"></i>
      <i class="fa fa-3x fa-mars-stroke"></i>
      <i class="fa fa-3x fa-mars-stroke-v"></i>
      <i class="fa fa-3x fa-mars-stroke-h"></i>
      <i class="fa fa-3x fa-neuter"></i>
      <i class="fa fa-3x fa-genderless"></i>
      <i class="fa fa-3x fa-facebook-official"></i>
      <i class="fa fa-3x fa-pinterest-p"></i>
      <i class="fa fa-3x fa-whatsapp"></i>
      <i class="fa fa-3x fa-server"></i>
      <i class="fa fa-3x fa-user-plus"></i>
      <i class="fa fa-3x fa-user-times"></i>
      <i class="fa fa-3x fa-hotel"></i>
      <i class="fa fa-3x fa-bed"></i>
      <i class="fa fa-3x fa-viacoin"></i>
      <i class="fa fa-3x fa-train"></i>
      <i class="fa fa-3x fa-subway"></i>
      <i class="fa fa-3x fa-medium"></i>
      <i class="fa fa-3x fa-yc"></i>
      <i class="fa fa-3x fa-y-combinator"></i>
      <i class="fa fa-3x fa-optin-monster"></i>
      <i class="fa fa-3x fa-opencart"></i>
      <i class="fa fa-3x fa-expeditedssl"></i>
      <i class="fa fa-3x fa-battery-4"></i>
      <i class="fa fa-3x fa-battery"></i>
      <i class="fa fa-3x fa-battery-full"></i>
      <i class="fa fa-3x fa-battery-3"></i>
      <i class="fa fa-3x fa-battery-three-quarters"></i>
      <i class="fa fa-3x fa-battery-2"></i>
      <i class="fa fa-3x fa-battery-half"></i>
      <i class="fa fa-3x fa-battery-1"></i>
      <i class="fa fa-3x fa-battery-quarter"></i>
      <i class="fa fa-3x fa-battery-0"></i>
      <i class="fa fa-3x fa-battery-empty"></i>
      <i class="fa fa-3x fa-mouse-pointer"></i>
      <i class="fa fa-3x fa-i-cursor"></i>
      <i class="fa fa-3x fa-object-group"></i>
      <i class="fa fa-3x fa-object-ungroup"></i>
      <i class="fa fa-3x fa-sticky-note"></i>
      <i class="fa fa-3x fa-sticky-note-o"></i>
      <i class="fa fa-3x fa-cc-jcb"></i>
      <i class="fa fa-3x fa-cc-diners-club"></i>
      <i class="fa fa-3x fa-clone"></i>
      <i class="fa fa-3x fa-balance-scale"></i>
      <i class="fa fa-3x fa-hourglass-o"></i>
      <i class="fa fa-3x fa-hourglass-1"></i>
      <i class="fa fa-3x fa-hourglass-start"></i>
      <i class="fa fa-3x fa-hourglass-2"></i>
      <i class="fa fa-3x fa-hourglass-half"></i>
      <i class="fa fa-3x fa-hourglass-3"></i>
      <i class="fa fa-3x fa-hourglass-end"></i>
      <i class="fa fa-3x fa-hourglass"></i>
      <i class="fa fa-3x fa-hand-grab-o"></i>
      <i class="fa fa-3x fa-hand-rock-o"></i>
      <i class="fa fa-3x fa-hand-stop-o"></i>
      <i class="fa fa-3x fa-hand-paper-o"></i>
      <i class="fa fa-3x fa-hand-scissors-o"></i>
      <i class="fa fa-3x fa-hand-lizard-o"></i>
      <i class="fa fa-3x fa-hand-spock-o"></i>
      <i class="fa fa-3x fa-hand-pointer-o"></i>
      <i class="fa fa-3x fa-hand-peace-o"></i>
      <i class="fa fa-3x fa-trademark"></i>
      <i class="fa fa-3x fa-registered"></i>
      <i class="fa fa-3x fa-creative-commons"></i>
      <i class="fa fa-3x fa-gg"></i>
      <i class="fa fa-3x fa-gg-circle"></i>
      <i class="fa fa-3x fa-tripadvisor"></i>
      <i class="fa fa-3x fa-odnoklassniki"></i>
      <i class="fa fa-3x fa-odnoklassniki-square"></i>
      <i class="fa fa-3x fa-get-pocket"></i>
      <i class="fa fa-3x fa-wikipedia-w"></i>
      <i class="fa fa-3x fa-safari"></i>
      <i class="fa fa-3x fa-chrome"></i>
      <i class="fa fa-3x fa-firefox"></i>
      <i class="fa fa-3x fa-opera"></i>
      <i class="fa fa-3x fa-internet-explorer"></i>
      <i class="fa fa-3x fa-tv"></i>
      <i class="fa fa-3x fa-television"></i>
      <i class="fa fa-3x fa-contao"></i>
      <i class="fa fa-3x fa-500px"></i>
      <i class="fa fa-3x fa-amazon"></i>
      <i class="fa fa-3x fa-calendar-plus-o"></i>
      <i class="fa fa-3x fa-calendar-minus-o"></i>
      <i class="fa fa-3x fa-calendar-times-o"></i>
      <i class="fa fa-3x fa-calendar-check-o"></i>
      <i class="fa fa-3x fa-industry"></i>
      <i class="fa fa-3x fa-map-pin"></i>
      <i class="fa fa-3x fa-map-signs"></i>
      <i class="fa fa-3x fa-map-o"></i>
      <i class="fa fa-3x fa-map"></i>
      <i class="fa fa-3x fa-commenting"></i>
      <i class="fa fa-3x fa-commenting-o"></i>
      <i class="fa fa-3x fa-houzz"></i>
      <i class="fa fa-3x fa-vimeo"></i>
      <i class="fa fa-3x fa-black-tie"></i>
      <i class="fa fa-3x fa-fonticons"></i>
      <i class="fa fa-3x fa-reddit-alien"></i>
      <i class="fa fa-3x fa-edge"></i>
      <i class="fa fa-3x fa-credit-card-alt"></i>
      <i class="fa fa-3x fa-codiepie"></i>
      <i class="fa fa-3x fa-modx"></i>
      <i class="fa fa-3x fa-fort-awesome"></i>
      <i class="fa fa-3x fa-usb"></i>
      <i class="fa fa-3x fa-product-hunt"></i>
      <i class="fa fa-3x fa-mixcloud"></i>
      <i class="fa fa-3x fa-scribd"></i>
      <i class="fa fa-3x fa-pause-circle"></i>
      <i class="fa fa-3x fa-pause-circle-o"></i>
      <i class="fa fa-3x fa-stop-circle"></i>
      <i class="fa fa-3x fa-stop-circle-o"></i>
      <i class="fa fa-3x fa-shopping-bag"></i>
      <i class="fa fa-3x fa-shopping-basket"></i>
      <i class="fa fa-3x fa-hashtag"></i>
      <i class="fa fa-3x fa-bluetooth"></i>
      <i class="fa fa-3x fa-bluetooth-b"></i>
      <i class="fa fa-3x fa-percent"></i>
      <i class="fa fa-3x fa-gitlab"></i>
      <i class="fa fa-3x fa-wpbeginner"></i>
      <i class="fa fa-3x fa-wpforms"></i>
      <i class="fa fa-3x fa-envira"></i>
      <i class="fa fa-3x fa-universal-access"></i>
      <i class="fa fa-3x fa-wheelchair-alt"></i>
      <i class="fa fa-3x fa-question-circle-o"></i>
      <i class="fa fa-3x fa-blind"></i>
      <i class="fa fa-3x fa-audio-description"></i>
      <i class="fa fa-3x fa-volume-control-phone"></i>
      <i class="fa fa-3x fa-braille"></i>
      <i class="fa fa-3x fa-assistive-listening-systems"></i>
      <i class="fa fa-3x fa-asl-interpreting"></i>
      <i class="fa fa-3x fa-american-sign-language-interpreting"></i>
      <i class="fa fa-3x fa-deafness"></i>
      <i class="fa fa-3x fa-hard-of-hearing"></i>
      <i class="fa fa-3x fa-deaf"></i>
      <i class="fa fa-3x fa-glide"></i>
      <i class="fa fa-3x fa-glide-g"></i>
      <i class="fa fa-3x fa-signing"></i>
      <i class="fa fa-3x fa-sign-language"></i>
      <i class="fa fa-3x fa-low-vision"></i>
      <i class="fa fa-3x fa-viadeo"></i>
      <i class="fa fa-3x fa-viadeo-square"></i>
      <i class="fa fa-3x fa-snapchat"></i>
      <i class="fa fa-3x fa-snapchat-ghost"></i>
      <i class="fa fa-3x fa-snapchat-square"></i>
      <i class="fa fa-3x fa-pied-piper"></i>
      <i class="fa fa-3x fa-first-order"></i>
      <i class="fa fa-3x fa-yoast"></i>
      <i class="fa fa-3x fa-themeisle"></i>
      <i class="fa fa-3x fa-google-plus-circle"></i>
      <i class="fa fa-3x fa-google-plus-official"></i>
      <i class="fa fa-3x fa-fa"></i>
      <i class="fa fa-3x fa-font-awesome"></i>
      <i class="fa fa-3x fa-handshake-o"></i>
      <i class="fa fa-3x fa-envelope-open"></i>
      <i class="fa fa-3x fa-envelope-open-o"></i>
      <i class="fa fa-3x fa-linode"></i>
      <i class="fa fa-3x fa-address-book"></i>
      <i class="fa fa-3x fa-address-book-o"></i>
      <i class="fa fa-3x fa-vcard"></i>
      <i class="fa fa-3x fa-address-card"></i>
      <i class="fa fa-3x fa-vcard-o"></i>
      <i class="fa fa-3x fa-address-card-o"></i>
      <i class="fa fa-3x fa-user-circle"></i>
      <i class="fa fa-3x fa-user-circle-o"></i>
      <i class="fa fa-3x fa-user-o"></i>
      <i class="fa fa-3x fa-id-badge"></i>
      <i class="fa fa-3x fa-drivers-license"></i>
      <i class="fa fa-3x fa-id-card"></i>
      <i class="fa fa-3x fa-drivers-license-o"></i>
      <i class="fa fa-3x fa-id-card-o"></i>
      <i class="fa fa-3x fa-quora"></i>
      <i class="fa fa-3x fa-free-code-camp"></i>
      <i class="fa fa-3x fa-telegram"></i>
      <i class="fa fa-3x fa-thermometer-4"></i>
      <i class="fa fa-3x fa-thermometer"></i>
      <i class="fa fa-3x fa-thermometer-full"></i>
      <i class="fa fa-3x fa-thermometer-3"></i>
      <i class="fa fa-3x fa-thermometer-three-quarters"></i>
      <i class="fa fa-3x fa-thermometer-2"></i>
      <i class="fa fa-3x fa-thermometer-half"></i>
      <i class="fa fa-3x fa-thermometer-1"></i>
      <i class="fa fa-3x fa-thermometer-quarter"></i>
      <i class="fa fa-3x fa-thermometer-0"></i>
      <i class="fa fa-3x fa-thermometer-empty"></i>
      <i class="fa fa-3x fa-shower"></i>
      <i class="fa fa-3x fa-bathtub"></i>
      <i class="fa fa-3x fa-s15"></i>
      <i class="fa fa-3x fa-bath"></i>
      <i class="fa fa-3x fa-podcast"></i>
      <i class="fa fa-3x fa-window-maximize"></i>
      <i class="fa fa-3x fa-window-minimize"></i>
      <i class="fa fa-3x fa-window-restore"></i>
      <i class="fa fa-3x fa-times-rectangle"></i>
      <i class="fa fa-3x fa-window-close"></i>
      <i class="fa fa-3x fa-times-rectangle-o"></i>
      <i class="fa fa-3x fa-window-close-o"></i>
      <i class="fa fa-3x fa-bandcamp"></i>
      <i class="fa fa-3x fa-grav"></i>
      <i class="fa fa-3x fa-etsy"></i>
      <i class="fa fa-3x fa-imdb"></i>
      <i class="fa fa-3x fa-ravelry"></i>
      <i class="fa fa-3x fa-eercast"></i>
      <i class="fa fa-3x fa-microchip"></i>
      <i class="fa fa-3x fa-snowflake-o"></i>
      <i class="fa fa-3x fa-superpowers"></i>
      <i class="fa fa-3x fa-wpexplorer"></i>
      <i class="fa fa-3x fa-meetup"></i>
    </div>
    <div>
      <a href="#"><i class="fa fa-home fa-fw"></i>&nbsp; Home</a>
      <a href="#"><i class="fa fa-book fa-fw"></i>&nbsp; Library</a>
      <a href="#"><i class="fa fa-pencil fa-fw"></i>&nbsp; Applications</a>
      <a href="#"><i class="fa fa-cog fa-fw"></i>&nbsp; Settings</a>
    </div>
    <div>
      <h4>大小控制</h4>
      <div>
        <span class="fa fa-camera-retro fa-lg"></span>
        <span class="fa fa-camera-retro fa-2x"></span>
        <span class="fa fa-camera-retro fa-3x"></span>
        <span class="fa fa-camera-retro fa-4x"></span>
        <span class="fa fa-camera-retro fa-5x"></span>
      </div>
    </div>
    <div>
      <h4>用于列表</h4>
      <div>
        <ul class="fa-ul">
          <li><i class="fa-li fa fa-check-square"></i>List icons</li>
          <li><i class="fa-li fa fa-check-square"></i>can be used</li>
          <li><i class="fa-li fa fa-spinner fa-spin"></i>as bullets</li>
          <li><i class="fa-li fa fa-square"></i>in lists</li>
        </ul>
      </div>
    </div>
    <div>
      <h4>边框与对齐</h4>
      <div>
        <i class="fa fa-quote-left fa-3x pull-left fa-border"></i>
        ...tomorrow we will run faster, stretch out our arms farther...
        And then one fine morning— So we beat on, boats against the
        current, borne back ceaselessly into the past.
      </div>
    </div>
    <div>
      <h4>动画</h4>
      <p>
        使用 fa-spin 类来使任意图标旋转，现在您还可以使用 fa-pulse 来使其进行8方位旋转。尤其适合 fa-spinner、fa-refresh 和 fa-cog 。 </p>
      <div>
        <i class="fa fa-spinner fa-spin fa-3x"></i>
        <i class="fa fa-circle-o-notch fa-spin fa-3x"></i>
        <i class="fa fa-refresh fa-spin fa-3x"></i>
        <i class="fa fa-cog fa-spin fa-3x"></i>
        <i class="fa fa-spinner fa-pulse fa-3x"></i>
      </div>
    </div>
    <div>
      <h4>旋转与翻转</h4>
      <p>使用 fa-rotate-* 和 fa-flip-* 类可以对图标进行任意旋转和翻转。 </p>
      <div>
        <i class="fa fa-shield"></i> normal<br>
        <i class="fa fa-shield fa-rotate-90"></i> fa-rotate-90<br>
        <i class="fa fa-shield fa-rotate-180"></i> fa-rotate-180<br>
        <i class="fa fa-shield fa-rotate-270"></i> fa-rotate-270<br>
        <i class="fa fa-shield fa-flip-horizontal"></i> fa-flip-horizontal<br>
        <i class="fa fa-shield fa-flip-vertical"></i> icon-flip-vertical
      </div>
    </div>
    <div>
      <h4>组合使用</h4>
      <div>
        <span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-twitter fa-stack-1x"></i>
      </span>
        fa-twitter on fa-square-o<br>
        <span class="fa-stack fa-lg">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-flag fa-stack-1x fa-inverse"></i>
        </span>
        fa-flag on fa-circle<br>
        <span class="fa-stack fa-lg">
          <i class="fa fa-square fa-stack-2x"></i>
          <i class="fa fa-terminal fa-stack-1x fa-inverse"></i>
        </span>
        fa-terminal on fa-square<br>
        <span class="fa-stack fa-lg">
          <i class="fa fa-camera fa-stack-1x"></i>
          <i class="fa fa-ban fa-stack-2x text-danger"></i>
        </span>
        fa-ban on fa-camera
      </div>
    </div>
    div>p+div
  </div>
</template>

<script>
export default {
  name: 'font-awesome'
}
</script>

<style scoped>
  div.icon-repository i{
    margin-right: 5px;
    margin-bottom: 5px;
  }
</style>
